### ISSUE TITLE
Support debug logging in workflows

### ISSUE THREAD

**Issue by smals-mavh** [belgif/workflows#1]
GitHub provides a checkbox: "Enable debug logging" for a workflow, but current workflows don't implement the flag of this checkbox:
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging

**Comment by pvdbosch** [comment]
Suggestion would be to add "-X -e" mvn command-line options when ACTIONS_STEP_DEBUG env variable is set to true
